### ISSUE TITLE
Incorrect location for belongsTo

### ISSUE THREAD

**Issue by tamr** [absszero/LaravelGoto#12]
For some reason it appends ".blade" trying to detect file location for belongsTo.

$this->belongsTo('App\Models\Weeez\MyNewShinyModel  becomes App\Models\Weeez\MyNewShinyModel.blade.php

Would be great to have goto's for other relations belongsToMany, hasMany..

Also noticed it appends ";" somewhere which prevents to jump to file.

**Comment by absszero** [comment]
> Also noticed it appends ";" somewhere which prevents to jump to file.

Hi, Could you give me an example about this, thank you.

```
Also noticed it appends ";" somewhere which prevents to jump to file.
```

**Comment by tamr** [comment]
This one for example, once removed it shows the path
`use App\Models\Shiny\NewModel as ShinyModel;`

Upd: oh, I just read the readme closely, hadn't noticed these are not supported yet
