### ISSUE TITLE
Open all translations in a single window

### ISSUE THREAD

**Issue by itsmewes** [absszero/LaravelGoto#15]
**Describe the bug**
I originally asked for a feature in [this Issue](https://github.com/absszero/LaravelGoto/issues/8). The feature request was picked up and added which was great! The feature had an extra option in the list to open all the translations files. For some reason this is no longer the case and that option is now missing. I've tried to see if I have missed anything in the settings, but couldn't spot anything. I'm not sure if this is a regression or was purposefully removed because it was causing some issue.

**To Reproduce**
1. Find a translation string.
2. Open the command prompt and find `Laravel Goto: Goto Implementation`.
3. A list of the translation files will show up, but not the option to open all of the translation files.

**Expected behavior**
An option to open all the translation files shows up and opens the files in a new window.

**Comment by absszero** [comment]
Hi, I've released a version 1.17.1, please install that and try again. thank you!

**Comment by itsmewes** [comment]
> Hi, I've released a version 1.17.1, please install that and try again. thank you!

Amazing, thank you so much!
