### ISSUE TITLE
does it support blade @include?

### ISSUE THREAD

**Issue by kolydart** [absszero/LaravelGoto#5]
Hi.
Thanks for the fantastic package!
When I click on a blade `@include('partial.items.show')`, it does not respond.
Is blade "@include" supported?

**Comment by absszero** [comment]
> Hi. Thanks for the fantastic package! When I click on a blade `@include('partial.items.show')`, it does not respond. Is blade "@include" supported?

Hi, 
I have released a new version [4.14.0](https://marketplace.visualstudio.com/items?itemName=absszero.vscode-laravel-goto) to support '@include' and other  blade directives.

**Comment by kolydart** [comment]
Thank you for the answer, @absszero. The version [you refered](https://marketplace.visualstudio.com/items?itemName=absszero.vscode-laravel-goto) is for the VS Code package. This package is for SublimeText. I am just mentioning it.
Best regards

**Comment by absszero** [comment]
> 

Sorry the mistake, I'll make a change for SublimeText later.

**Comment by absszero** [comment]
> Thank you for the answer, @absszero. The version [you refered](https://marketplace.visualstudio.com/items?itemName=absszero.vscode-laravel-goto) is for the VS Code package. This package is for SublimeText. I am just mentioning it. Best regards

A new version is released. https://packagecontrol.io/packages/Laravel%20Goto 👍
